# Generated by Django 3.2.12 on 2024-10-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_country_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='nation',
            field=models.CharField(max_length=56, unique=True),
        ),
    ]
